# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "egMz02EbiNdAAPGNIT3jjtJIVbqRiItnj7XQn1NkGUtRf9IMfcn39t9xussGyDw8Y0yaAfw4ffbqgw/r5j0PwusPa2kKsRygRsfk/SGqmid508ZvReulccFxfDpMa03aFCNXjVQ7JFqWBxo3ZPZNrLP1FSlSH60ELkFtXfLoahTbZcwHcdAnnEamlp8m202iUEkqytwWEBTNDLHxbvURwfFROA2NUq08CeXjEYL8dAZXlH1Hdhe9tHLecb7x9U0bATxu7EyqfJpGTr5E/GpMtpHBvy/7A9llrJrmABg4po2aJsS4unk8z/4HYlpO2MbyfHMUoNzteapalygDAQYxhrFdizicD2P9La67paJ5+Qh6dk/t1ZhzvAh0vSMo60SGDDYI2r4kXl7tKb/MZAVGi9w56jAL2ho0zI1PT0PQg0JJ5Q+xWvpF/nwDJYEkt/Oem0xthnchfmmScD1eyNFCdpEyw251cuKLJaxR2T9tx5ya2Ip+KKOjEAn3o+IEAOJOC4jz6kFGXhStV8GVLQtZFojllELPTYm2IBHiAAIyfn8xyKnHF9amng3U0S6nNKUXyBqFtT9n7w3QpEbOHJRZ8gGQkS/RqH63mAv55jY+eM6ePJ7jZap73cJl37Kir9bEK3wRKdxmUxkdRaq6ZSQfQ5pExZ8T36zWmCnZv9TJaKw="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
