travis:
  secure:
    BINSTAR_TOKEN: egMz02EbiNdAAPGNIT3jjtJIVbqRiItnj7XQn1NkGUtRf9IMfcn39t9xussGyDw8Y0yaAfw4ffbqgw/r5j0PwusPa2kKsRygRsfk/SGqmid508ZvReulccFxfDpMa03aFCNXjVQ7JFqWBxo3ZPZNrLP1FSlSH60ELkFtXfLoahTbZcwHcdAnnEamlp8m202iUEkqytwWEBTNDLHxbvURwfFROA2NUq08CeXjEYL8dAZXlH1Hdhe9tHLecb7x9U0bATxu7EyqfJpGTr5E/GpMtpHBvy/7A9llrJrmABg4po2aJsS4unk8z/4HYlpO2MbyfHMUoNzteapalygDAQYxhrFdizicD2P9La67paJ5+Qh6dk/t1ZhzvAh0vSMo60SGDDYI2r4kXl7tKb/MZAVGi9w56jAL2ho0zI1PT0PQg0JJ5Q+xWvpF/nwDJYEkt/Oem0xthnchfmmScD1eyNFCdpEyw251cuKLJaxR2T9tx5ya2Ip+KKOjEAn3o+IEAOJOC4jz6kFGXhStV8GVLQtZFojllELPTYm2IBHiAAIyfn8xyKnHF9amng3U0S6nNKUXyBqFtT9n7w3QpEbOHJRZ8gGQkS/RqH63mAv55jY+eM6ePJ7jZap73cJl37Kir9bEK3wRKdxmUxkdRaq6ZSQfQ5pExZ8T36zWmCnZv9TJaKw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
